# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html for more information

[sncast.default]
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
account = "starkash"
wait_params = { timeout = 500, retry_interval = 10 }
block_explorer = "StarkScan"
